name: Test

on:
  push:
    branches:
      - main
      - workflows # for testing
  pull_request:
    branches:
      - main

jobs:
  policy-manager:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: install system dependencies
        run: sudo apt-get install -y cmake gcc g++ protobuf-compiler

      - name: cargo test
        run: cargo test --all-features
        working-directory: ./services/policy-manager
